[package]
name = "cri-headings"
version = "0.1.0"
edition = "2021"
authors = [ "William Blackerby <wmblackerby@gmail.com>" ]

[dependencies]
clap = { version = "4.3.0", features = ["derive"] }
reqwest = { version = "0.11.23", features = ["json"] }
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
